# Generated by Django 4.2.11 on 2024-05-17 17:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myschool.core_attrs
import myschool.plugins.generate_filename
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session', models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033')], max_length=250, null=True)),
                ('code', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Classes',
                'verbose_name_plural': 'Classes',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
            bases=('auth.user', myschool.core_attrs.CoreAttrs),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myschool.classes')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ('name',),
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='SectionsNames',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(upload_to=myschool.plugins.generate_filename.generate_filename)),
                ('show_on_frontend', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
            bases=('auth.user', myschool.core_attrs.CoreAttrs),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField(null=True)),
                ('days', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=250, null=True)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_subject_rel', to='myschool.subjects')),
            ],
            options={
                'verbose_name': 'TimeTable',
                'verbose_name_plural': 'TimeTable',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='SubjectSelection',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session', models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033')], max_length=250, null=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_classes_selected', to='myschool.classes')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_sections_selected', to='myschool.sections')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_subject_selected', to='myschool.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_teacher_selected', to='myschool.teachers')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_term_selected', to='myschool.term')),
            ],
            options={
                'verbose_name': 'Subject Selection',
                'verbose_name_plural': 'Subject Selections',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('parent_registration_code', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(upload_to=myschool.plugins.generate_filename.generate_filename)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.classes')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.sections')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('auth.user', myschool.core_attrs.CoreAttrs),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='sections',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myschool.sectionsnames'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session', models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033')], max_length=250, null=True)),
                ('result', models.JSONField(default=list)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.classes')),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.sections')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.teachers')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.term')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='AttendanceRecords',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_code', models.CharField(editable=False, max_length=150, null=True)),
                ('morning', models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present')], max_length=150, null=True)),
                ('afternoon', models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present')], max_length=150, null=True)),
                ('month_name', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=250, null=True)),
                ('day_name', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=250, null=True)),
                ('attendance_date', models.CharField(blank=True, max_length=250, null=True)),
                ('attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rel', to='myschool.attendance')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rel_recorder', to='myschool.students')),
            ],
            options={
                'verbose_name': 'Student Record',
                'verbose_name_plural': 'Student Records',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rel_classes_selected', to='myschool.classes'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rel_sections_selected', to='myschool.sections'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rel_subject_selected', to='myschool.subjects'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rel_teacher_selected', to='myschool.teachers'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_rel_term_selected', to='myschool.term'),
        ),
    ]
