# Generated by Django 4.2.11 on 2024-05-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionsnames',
            options={'verbose_name': 'Section Name', 'verbose_name_plural': 'Section Names'},
        ),
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_names_rel', to='myschool.sectionsnames'),
        ),
    ]
