# Generated by Django 4.2.11 on 2024-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0002_alter_sectionsnames_options_alter_sections_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ('id',), 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='subjectselection',
            options={'ordering': ('-id',), 'verbose_name': 'Teacher Subject', 'verbose_name_plural': 'Teacher Subjects'},
        ),
        migrations.AddField(
            model_name='students',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
