# Generated by Django 4.2.11 on 2024-05-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0004_parents_code_parents_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='term',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
    ]
