# Generated by Django 4.2.11 on 2024-05-29 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myschool.core_attrs
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0005_alter_classes_desc_alter_sections_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPromotion',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_classes_promotion', to='myschool.classes')),
                ('current_sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_sections_promotion', to='myschool.sections')),
                ('previous_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_previous_classes_promotion', to='myschool.classes')),
                ('previous_sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_previous_sections_promotion', to='myschool.sections')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_promotion', to='myschool.students')),
            ],
            options={
                'verbose_name': 'Student Promotion',
                'verbose_name_plural': 'Student Promotions',
                'ordering': ('-id',),
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
    ]
