# Generated by Django 4.2.11 on 2024-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0006_studentpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpromotion',
            name='promotion_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
