# Generated by Django 4.2.11 on 2024-05-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0007_studentpromotion_promotion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpromotion',
            name='promotion_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
