# Generated by Django 4.2.11 on 2024-05-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0008_alter_studentpromotion_promotion_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ('-id',), 'verbose_name': 'Classes', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=150, null=True),
        ),
    ]
