# Generated by Django 4.2.11 on 2024-05-30 07:20

from django.db import migrations, models
import myschool.plugins.generate_filename


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0009_alter_classes_options_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=myschool.plugins.generate_filename.generate_filename),
        ),
    ]
