# Generated by Django 4.2.11 on 2024-07-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myschool.core_attrs
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myschool', '0011_alter_results_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultComment',
            fields=[
                ('created', models.DateField(auto_created=True, default=django.utils.timezone.now, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session', models.CharField(choices=[('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029'), ('2029-2030', '2029-2030'), ('2030-2031', '2030-2031'), ('2031-2032', '2031-2032'), ('2032-2033', '2032-2033')], max_length=250, null=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.classes')),
                ('commentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_comment_related', to='myschool.teachers')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subjects')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.term')),
            ],
            options={
                'verbose_name': 'Result Comments',
                'verbose_name_plural': 'Result Comment',
            },
            bases=(models.Model, myschool.core_attrs.CoreAttrs),
        ),
    ]
