# Generated by Django 4.2.11 on 2024-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0012_resultcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultcomment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
