# Generated by Django 4.2.11 on 2024-07-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0014_alter_resultcomment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='resultcomment',
            name='commentor',
        ),
        migrations.RemoveField(
            model_name='resultcomment',
            name='student',
        ),
    ]
