# Generated by Django 4.2.11 on 2024-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0015_remove_resultcomment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultcomment',
            name='comment',
            field=models.JSONField(null=True),
        ),
    ]
