# Generated by Django 4.2.11 on 2024-05-17 19:49

import appcore.core_attrs
import appcore.plugins.custom_plugins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=appcore.plugins.custom_plugins.generate_filename)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
            bases=(models.Model, appcore.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='Plugins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_type', models.CharField(max_length=150)),
                ('status', models.BooleanField(choices=[(True, 'Activate'), (False, 'Deactivate')], default=False)),
                ('name', models.CharField(max_length=150)),
                ('file_path', models.CharField(blank=True, max_length=250, null=True)),
                ('template_file', models.CharField(blank=True, max_length=250, null=True)),
                ('directory', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettingLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('favicon', models.ImageField(upload_to='logo')),
            ],
            options={
                'verbose_name': 'Setting Logo',
                'verbose_name_plural': 'Settings Logo',
            },
            bases=(models.Model, appcore.core_attrs.CoreAttrs),
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('context', models.JSONField()),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'db_table': '',
                'managed': True,
            },
            bases=(models.Model, appcore.core_attrs.CoreAttrs),
        ),
    ]
