# Generated by Django 4.2.11 on 2024-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('code', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False, help_text='Checks online status.')),
                ('permissions', models.CharField(blank=True, choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('accountant', 'Accountant')], max_length=150, null=True)),
                ('finger_signature', models.CharField(blank=True, max_length=350, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Authusers',
                'verbose_name_plural': 'Authusers',
            },
        ),
    ]
